import {Reveal} from '@/components/motion/interactions';
import {NumberTicker} from '@/components/motion/number-ticker';
import {useEffect,useState} from 'react';
import {Search,ArrowRight,Plus,BookOpen,FileText,Clock3,ShieldCheck,ChevronRight} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {useResource,navigate} from '@/lib/api';
import {Loading,ErrorNotice} from './common';
import type {QuestionSet} from '../../shared/domain';

type SetSummary=Pick<QuestionSet,'id'|'title'|'input'|'revision'|'review_status'|'created_at'|'updated_at'|'parent_id'>;
export function BankPage(){
 const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [selectedId,setSelectedId]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setOffset(0)},250);return()=>clearTimeout(timer)},[search]);
 const {data,error,reload}=useResource<SetSummary[]>(`/api/sets?q=${encodeURIComponent(query)}&offset=${offset}`);
 const selected=data?.find(s=>s.id===selectedId)||data?.[0];
 const reviewed=data?.filter(s=>s.review_status==='reviewed').length||0;
 return <div className="space-y-6"><header className="studio-heading"><div><p className="eyebrow">TU BIBLIOTECA DE TRABAJO</p><h1 className="page-title">Banco de preguntas</h1><p className="page-description">Un lugar para revisar, mejorar y volver a utilizar tus conjuntos.</p></div><Button onClick={()=>navigate('new')}><Plus/>Crear preguntas</Button></header>
 {data&&<div><div className="studio-bank-stats">{[{icon:BookOpen,n:data.length,label:'Conjuntos',tone:'mint'},{icon:Clock3,n:data.length-reviewed,label:'Pendientes de revisión',tone:'peach'},{icon:ShieldCheck,n:reviewed,label:'Revisión registrada',tone:'lavender'}].map(({icon:Icon,n,label,tone})=><div key={label}><span className={`studio-stat-icon ${tone}`}><Icon size={23}/></span><div><strong><NumberTicker value={n}/></strong><p>{label}</p></div></div>)}</div><p className="studio-hint mt-2">Conteos de esta página{query?' con la búsqueda actual':''}.</p></div>}
 <ErrorNotice message={error} onRetry={reload}/><div className="studio-bank-layout"><section className="studio-bank-list" aria-label="Conjuntos guardados"><header><h2>Todos los conjuntos</h2><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-10" aria-label="Buscar preguntas" maxLength={200} placeholder="Buscar por título, tema o especialidad" value={search} onChange={e=>setSearch(e.target.value)}/></div></header>{!data&&!error?<div className="px-6"><Loading/></div>:data?.length?<Table><TableHeader><TableRow><TableHead>Conjunto</TableHead><TableHead>Estado</TableHead><TableHead>Actualizado</TableHead><TableHead><span className="sr-only">Acciones</span></TableHead></TableRow></TableHeader><TableBody>{data.map(set=><TableRow key={set.id} data-state={selected?.id===set.id?'selected':undefined}><TableCell><button className="studio-bank-row" aria-label={`Vista previa de ${set.title}`} aria-pressed={selected?.id===set.id} onClick={()=>setSelectedId(set.id)}><FileText size={22}/><span><strong>{set.title}</strong><small>{set.input.specialty} · {set.input.count} preguntas</small></span></button></TableCell><TableCell><Badge variant="secondary" className={set.review_status==='reviewed'?'studio-reviewed':'studio-pending'}>{set.review_status==='reviewed'?'Revisión registrada':'Pendiente de revisión'}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{new Date(set.updated_at).toLocaleDateString('es-MX')}<span className="mt-1 block">Versión {set.revision}</span></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Abrir conjunto ${set.title}`} onClick={()=>navigate(`set/${set.id}`)}><ChevronRight/></Button></TableCell></TableRow>)}</TableBody></Table>:<p className="studio-bank-empty">{error?'No se pudieron cargar los conjuntos.':query?'No hay conjuntos que coincidan con tu búsqueda.':'Tus preguntas aparecerán aquí cuando completes la primera generación.'}</p>}
 <footer><Button variant="outline" disabled={offset===0||!data} onClick={()=>setOffset(o=>Math.max(0,o-50))}>Anterior</Button><span>Página {Math.floor(offset/50)+1}</span><Button variant="outline" disabled={!data||data.length<50} onClick={()=>setOffset(o=>o+50)}>Siguiente</Button></footer></section>
 {selected&&<aside className="studio-bank-preview" aria-label="Vista previa del conjunto"><Reveal key={selected.id}><span className="studio-stat-icon lavender"><BookOpen size={25}/></span><p className="eyebrow mt-6">VISTA PREVIA</p><h2>{selected.title}</h2><p className="studio-hint mt-2">{selected.input.specialty}</p><div className="my-5 flex flex-wrap gap-2"><Badge variant="outline">{selected.input.count} preguntas</Badge><Badge variant="outline" className="capitalize">{selected.input.difficulty}</Badge></div><Badge variant="secondary">{selected.review_status==='reviewed'?'Revisión registrada':'Pendiente de revisión'}</Badge><dl className="studio-summary-list"><div><dt>Formato</dt><dd className="capitalize">{selected.input.format}</dd></div><div><dt>Enfoque</dt><dd className="capitalize">{selected.input.questionType}</dd></div><div><dt>Versión</dt><dd>{selected.revision}</dd></div></dl><Button className="studio-primary" onClick={()=>navigate(`set/${selected.id}`)}>Abrir conjunto<ArrowRight/></Button><p className="studio-hint">Revisa, edita, exporta o contesta las preguntas desde el conjunto.</p></Reveal></aside>}
 </div></div>;
}
