import {ActionButton,AnimatedUpload} from '@/components/motion/interactions';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import { ArrowRight, FileText, Loader2, Check, Plus, Stethoscope } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { Card,CardHeader,CardTitle,CardContent } from '@/components/ui/card';
import { Alert,AlertTitle,AlertDescription } from '@/components/ui/alert';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {StudioSection,FormatChoice,RequestSummary,AcademicNote} from '@/components/studio';
import { api,json,navigate,useResource } from '@/lib/api';
import {readGenerationDraft,generationIssue} from '@/lib/generation-draft';
import { RunInput,difficulties } from '../../shared/domain';
import { Choice,Field,ErrorNotice,states,type Config,type Doc,type Run,type Status } from './common';
const defaults={specialty:'Medicina interna',topic:'Diabetes tipo 2: control glucémico',subtopic:'',difficulty:'básica',count:3,instructions:'',questionType:'mixto',optionCount:4,format:'independientes',caseCount:1,questionsPerCase:2,sourceMode:'biblioteca',sourceIds:[]} as RunInput;
export function GeneratePage(){
 const [form,setForm]=useState<RunInput>(()=>{try{return readGenerationDraft(localStorage.getItem('enarm-generation-draft'),defaults)}catch{return defaults}});
 const [draftWarning,setDraftWarning]=useState('');const [review,setReview]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [notice,setNotice]=useState('');
 const pending=useRef<{serialized:string;key:string}|null>(null);
 const {data:docs,error:docsError,reload:reloadDocs}=useResource<Doc[]>('/api/documents');const {data:config,error:configError}=useResource<Config>('/api/config');const {data:status,error:statusError}=useResource<Status>('/api/status',10000);const {data:runs,reload:reloadRuns}=useResource<Run[]>('/api/runs',3000);
 const [runId,setRunId]=useState(()=>sessionStorage.getItem('enarm-current-run')||'');
 const current=runs?.find(r=>r.id===runId);const document=docs?.find(d=>d.id===form.documentId);
 function change<K extends keyof RunInput>(key:K,value:RunInput[K]){setForm(f=>({...f,[key]:value}));}
 useEffect(()=>{try{localStorage.setItem('enarm-generation-draft',JSON.stringify({...form,count:form.format==='seriadas'?form.caseCount*form.questionsPerCase:form.count}));setDraftWarning('')}catch{setDraftWarning('No se pudo guardar el borrador en este navegador. Conserva esta pestaña abierta.')}},[form]);
 const total=form.format==='seriadas'?form.caseCount*form.questionsPerCase:form.count;
 async function upload(file:File|undefined){if(!file)return;setError('');setNotice('');if(!file.size){setError('El archivo está vacío. Selecciona un documento con contenido.');return;}if(!/\.(pdf|txt)$/i.test(file.name)){setError('Selecciona un archivo PDF o TXT.');return;}if(file.size>5*1024*1024){setError('El documento supera 5 MB.');return;}setUploading(true);try{const body=new FormData();body.append('file',file);const d=await api<Doc>('/api/documents',{method:'POST',body});setForm(f=>({...f,documentId:d.id,sourceMode:f.sourceMode==='ambos'?'ambos':'documento'}));reloadDocs();setNotice(d.extraction_status==='ready'?'Documento cargado y texto extraído.':d.extraction_error||'Documento guardado; requiere revisión.');}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
 async function submit(){setError('');setNotice('');const issue=generationIssue(form);if(issue){setError(issue.message);globalThis.document.getElementById(issue.field)?.focus();return;}const parsed=RunInput.safeParse({...form,count:total});if(!parsed.success){setError('Revisa los parámetros de la solicitud.');return;}setBusy(true);try{const serialized=JSON.stringify(parsed.data);if(pending.current?.serialized!==serialized)pending.current={serialized,key:crypto.randomUUID()};const run=await api<Run>('/api/runs',{...json('POST',parsed.data),headers:{'Content-Type':'application/json','Idempotency-Key':pending.current.key}});setRunId(run.id);sessionStorage.setItem('enarm-current-run',run.id);pending.current=null;setReview(false);reloadRuns();setNotice('Solicitud guardada. Puedes salir y volver mientras se generan las preguntas.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const disabled=busy||uploading||status?.generation!=='configured'||(form.sourceMode!=='biblioteca'&&document?.extraction_status==='failed');
 const sourceTitles=config?.library.filter(s=>form.sourceIds.includes(s.id)).map(s=>s.title)||[];
 function reviewRequest(e:FormEvent){e.preventDefault();setError('');const issue=generationIssue(form);if(issue){setError(issue.message);globalThis.document.getElementById(issue.field)?.focus();return;}const parsed=RunInput.safeParse({...form,count:total});if(!parsed.success){setError('Revisa los parámetros de la solicitud.');return;}setReview(true);}
 return <div className="space-y-6"><header className="studio-heading"><div><p className="eyebrow">DISEÑA TU PRÓXIMA SESIÓN</p><h1 className="page-title">¿Qué vamos a evaluar?</h1><p className="page-description">Convierte un tema y sus fuentes en preguntas que puedas revisar y mejorar.</p></div><span className="studio-heading-icon"><Stethoscope size={34}/></span></header>
 {status&&status.generation!=='configured'&&<Alert><AlertTitle>Generación pendiente de activación</AlertTitle><AlertDescription>Puedes preparar solicitudes y cargar documentos. La generación se habilitará cuando el servicio esté configurado y disponible.</AlertDescription></Alert>}
 <ErrorNotice message={review?'':error}/><ErrorNotice message={docsError||configError||statusError}/>{notice&&<p role="status" className="studio-notice">{notice}</p>}
 <div className="studio-compose"><form noValidate id="generation-form" className="studio-form" onSubmit={reviewRequest}>
 <StudioSection number="01" title="Contenido clínico" description="Define el tema que quieres evaluar.">
 <Field id="specialty" label="Especialidad"><Choice id="specialty" value={form.specialty} onChange={v=>setForm(f=>({...f,specialty:v,sourceIds:[]}))} items={['Medicina interna','Pediatría','Ginecología y obstetricia','Cirugía general'].map(v=>[v,v])}/></Field>
 <Field id="topic" label="Tema"><Input id="topic" value={form.topic} onChange={e=>change('topic',e.target.value)} required maxLength={200} aria-describedby="topic-hint"/><p id="topic-hint" className="studio-hint">Elige un tema concreto para orientar los casos y sus fuentes.</p></Field>
 <details className="studio-optional"><summary><Plus size={16}/>Añadir subtema e instrucciones<span>Opcional</span></summary><div className="space-y-5"><Field id="subtopic" label="Subtema (opcional)"><Input id="subtopic" value={form.subtopic} onChange={e=>change('subtopic',e.target.value)} maxLength={200} placeholder="Por ejemplo, criterios diagnósticos"/></Field><Field id="instructions" label="Instrucciones adicionales (opcional)"><Textarea id="instructions" value={form.instructions} onChange={e=>change('instructions',e.target.value)} maxLength={2000} placeholder="Describe el enfoque o las características del caso ficticio."/></Field></div></details>
 </StudioSection>
 <StudioSection number="02" title="Estructura del conjunto" description="Decide cómo se presentan y contestan los casos.">
 <FormatChoice value={form.format} onChange={v=>change('format',v)}/>
 <div className="studio-related">{form.format==='seriadas'?<><Field id="caseCount" label="Número de casos"><Input id="caseCount" type="number" min={1} max={5} value={form.caseCount} onChange={e=>change('caseCount',Number(e.target.value))} required/></Field><Field id="questionsPerCase" label="Preguntas por caso"><Input id="questionsPerCase" type="number" min={2} max={5} value={form.questionsPerCase} onChange={e=>change('questionsPerCase',Number(e.target.value))} required/></Field></>:<Field id="count" label="Cantidad de preguntas"><Input id="count" type="number" min={1} max={10} value={form.count} onChange={e=>change('count',Number(e.target.value))} required/></Field>}
 <Field id="optionCount" label="Opciones por pregunta"><Choice id="optionCount" value={String(form.optionCount)} onChange={v=>change('optionCount',Number(v))} items={[3,4,5].map(v=>[String(v),`${v} opciones · una correcta`])}/></Field></div>
 <p className={'studio-equation '+(total>10?'text-destructive':'')}>{form.format==='seriadas'?`${form.caseCount} ${form.caseCount===1?'caso':'casos'} × ${form.questionsPerCase} preguntas = `:''}<strong>{total} preguntas en total</strong><span>Máximo 10 por solicitud</span></p>
 <fieldset><legend className="studio-legend">Dificultad</legend><RadioGroup aria-label="Dificultad" aria-describedby="difficulty-hint" className="studio-segments" value={form.difficulty} onValueChange={v=>change('difficulty',v as RunInput['difficulty'])}>{Object.keys(difficulties).map(v=><label className={form.difficulty===v?'selected':''} key={v}><RadioGroupItem value={v} aria-label={v}/><span className="capitalize">{v}</span></label>)}</RadioGroup><p className="studio-hint mt-3" id="difficulty-hint">{difficulties[form.difficulty]}</p></fieldset>
 <Field id="questionType" label="Tipo de pregunta"><Choice id="questionType" value={form.questionType} onChange={v=>change('questionType',v as RunInput['questionType'])} items={['diagnóstico','tratamiento','estudios','prevención','mixto'].map(v=>[v,v])}/></Field>
 </StudioSection>
 <StudioSection number="03" title="Fuentes de referencia" description="Elige la evidencia que guiará la redacción.">
 <fieldset><legend className="studio-legend">Origen de la información</legend><RadioGroup aria-label="Origen de la información" className="studio-segments" value={form.sourceMode} onValueChange={v=>change('sourceMode',v as RunInput['sourceMode'])}>{[['biblioteca','Biblioteca'],['documento','Mi documento'],['ambos','Ambos']].map(([v,l])=><label key={v} className={form.sourceMode===v?'selected':''}><RadioGroupItem value={v} aria-label={l}/>{l}</label>)}</RadioGroup></fieldset>
 {form.sourceMode!=='biblioteca'&&<div className="space-y-4"><Field id="document" label="Documento propio"><Choice id="document" value={form.documentId||'none'} onChange={v=>change('documentId',v==='none'?undefined:v)} items={[["none","Selecciona un documento"],...(docs||[]).map(d=>[d.id,d.filename] as [string,string])]}/></Field><AnimatedUpload busy={uploading} onUpload={file=>void upload(file)} onError={setError}/>
 {document&&<div className="studio-source"><FileText size={20}/><div><strong>{document.filename}</strong><p className={document.extraction_status==='failed'?'text-destructive':''}>{document.extraction_status==='ready'?'Texto disponible para generar':document.extraction_error||'Se extraerá el texto al generar.'}</p><a href={`/api/documents/${document.id}/download`} className="text-primary underline">Descargar original</a></div></div>}</div>}
 {form.sourceMode!=='documento'&&<fieldset className="space-y-3"><legend className="studio-legend">Fuentes de la biblioteca</legend><p className="studio-hint">Sin selección se usa la fuente predeterminada de la especialidad. <a href="#sources" className="text-primary underline">Revisa edición y cobertura.</a></p>{config?.library.filter(s=>s.specialty===form.specialty).map(s=><label key={s.id} className="studio-source cursor-pointer"><Checkbox checked={form.sourceIds.includes(s.id)} onCheckedChange={checked=>change('sourceIds',checked?[...form.sourceIds,s.id]:form.sourceIds.filter(id=>id!==s.id))}/><span><strong>{s.title}</strong><small>{s.edition}</small></span></label>)}</fieldset>}
 <p className="studio-hint">El contenido se enviará al proveedor de IA para generar y revisar. Usa material público o ficticio, sin datos personales.</p>
 </StudioSection><p className="studio-hint" role={draftWarning?'status':undefined}>{draftWarning||'Tu configuración se guarda automáticamente en este navegador.'}</p>
 </form>
 <aside className="studio-context"><div className="studio-sticky-summary"><div className="studio-summary"><RequestSummary form={form} documentName={document?.filename}/><Button id="review-request" type="submit" form="generation-form" className="studio-primary" disabled={disabled}>Revisar y generar<ArrowRight/></Button><p className="studio-hint text-center">Verás un resumen antes de enviar.</p></div><AcademicNote/></div>
 {current&&<Card className="shadow-none"><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-3">Tu solicitud<Badge variant={current.status==='failed'?'destructive':'secondary'}>{states[current.status]}</Badge></CardTitle></CardHeader><CardContent className="space-y-4"><p className="font-medium break-words">{current.input.topic}</p>{['queued','processing','retrying'].includes(current.status)&&<p className="flex items-start gap-2 text-sm leading-6 text-muted-foreground"><Loader2 className="mt-1 size-4 shrink-0 animate-spin"/>Se consultan fuentes, se redactan preguntas y se comprueban las referencias. Puede tomar varios minutos.</p>}{current.error&&<p role="alert" className="text-sm text-destructive">{current.error}</p>}{current.result?.setId&&<Button className="h-11 w-full" onClick={()=>navigate(`set/${current.result!.setId}`)}><Check/>Revisar preguntas</Button>}</CardContent></Card>}
 <Card className="shadow-none"><CardHeader><CardTitle>Solicitudes recientes</CardTitle></CardHeader><CardContent className="space-y-2">{runs?.length?runs.map(run=><Button type="button" variant="ghost" key={run.id} className="h-auto min-h-16 w-full justify-start p-3 text-left whitespace-normal" onClick={()=>{setRunId(run.id);if(run.result?.setId)navigate(`set/${run.result.setId}`)}}><FileText className="text-primary"/><span className="min-w-0"><span className="block break-words">{run.input.topic}</span><span className="mt-1 block text-xs font-normal text-muted-foreground">{states[run.status]} · {new Date(run.created_at).toLocaleDateString('es-MX')}</span></span></Button>):<p className="studio-hint">Aquí aparecerán tus solicitudes.</p>}<Button variant="link" asChild><a href="#bank">Ver banco de preguntas<ArrowRight/></a></Button></CardContent></Card>
 </aside></div>
 <Dialog open={review} onOpenChange={v=>{if(!busy)setReview(v)}}><DialogContent className="studio-review-dialog" showCloseButton={!busy} onCloseAutoFocus={event=>{event.preventDefault();globalThis.document.getElementById("review-request")?.focus()}}><DialogHeader><DialogTitle>Revisa tu solicitud</DialogTitle><DialogDescription>Confirma los parámetros y las fuentes antes de generar.</DialogDescription></DialogHeader><RequestSummary form={form} documentName={document?.filename} sourceTitles={sourceTitles} detailed/><ErrorNotice message={error}/><p className="studio-hint">El contenido se enviará al proveedor de IA. El resultado requiere revisión académica.</p><ActionButton disabled={disabled} loading={busy} loadingText="Enviando solicitud…" onClick={()=>void submit()}><ArrowRight/>Generar preguntas</ActionButton><Button variant="ghost" disabled={busy} onClick={()=>setReview(false)}>Volver a editar</Button></DialogContent></Dialog>
 </div>;
}
