import {motion} from 'motion/react';
import {AnimatedGroup} from '@/components/motion/animated-group';
import {NumberTicker} from '@/components/motion/number-ticker';
import {useMotionPreference} from '@/components/motion/preferences';
import {ArrowRight,ArrowUpRight,BookOpen,CalendarDays,Check,ClipboardCheck,Clock3,FileQuestion,FolderOpen,Plus,ShieldCheck,Sparkles} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Card} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Skeleton} from '@/components/ui/skeleton';
import {useResource} from '@/lib/api';
import {ErrorNotice} from './common';
import type {DashboardData} from '../../shared/dashboard';

const number=(value:number)=>value.toLocaleString('es-MX');
export function HomePage(){
 const {data,error,reload}=useResource<DashboardData>('/api/dashboard',30000);
 return <><header className="studio-heading home-heading"><div><p className="eyebrow">TU ESPACIO ACADÉMICO</p><h1 className="page-title">Un buen día para aprender.</h1><p className="page-description">Tus preguntas, tus fuentes y tu siguiente paso. Todo en un lugar.</p></div><span className="home-date"><CalendarDays size={16}/>{new Date().toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'})}</span></header><ErrorNotice message={error} onRetry={reload}/>{data?<HomeDashboard data={data}/>:!error?<div className="home-loading" role="status" aria-label="Cargando resumen"><Skeleton className="h-48 rounded-2xl"/><div className="home-metrics">{[1,2,3,4].map(i=><Skeleton key={i} className="h-36 rounded-2xl"/>)}</div><Skeleton className="h-72 rounded-2xl"/></div>:null}</>;
}

export function HomeDashboard({data}:{data:DashboardData}){
 const {reduced}=useMotionPreference();
 const {totals,activity,recent,nextReview,specialties}=data;
 const percent=totals.sets?Math.round(totals.reviewed/totals.sets*100):0;
 const weekTotal=activity.reduce((sum,d)=>sum+d.sets,0);
 const maximum=Math.max(1,...activity.map(d=>d.sets));
 const metrics=[{label:'Preguntas en tu banco',value:totals.questions,detail:'Disponibles para estudiar',icon:FileQuestion,tone:'blue'}, {label:'Conjuntos creados',value:totals.sets,detail:'Tu biblioteca de trabajo',icon:FolderOpen,tone:'lavender'}, {label:'Por revisar',value:totals.pending,detail:'Conjuntos sin revisión registrada',icon:Clock3,tone:'peach'}, {label:'Pruebas completadas',value:totals.practices,detail:'Intentos finalizados',icon:ClipboardCheck,tone:'mint'}];
 return <div className="home-dashboard">
  <section className="home-hero" aria-labelledby="home-hero-title"><div><span className="home-hero-label"><Sparkles size={15}/> DEL CONOCIMIENTO A LA PRÁCTICA</span><h2 id="home-hero-title">Tu próxima sesión<br/>empieza con una pregunta.</h2><p>Elige un tema, reúne tus fuentes y construye<br className="home-desktop-break"/> un conjunto a tu medida.</p><Button asChild className="home-hero-button"><a href="#new"><Plus size={17}/>Crear preguntas<ArrowRight size={17}/></a></Button></div><div className="home-hero-art" aria-hidden="true"><div className="home-orbit"/><div className="home-paper back"/><div className="home-paper"><span className="home-paper-icon"><BookOpen size={28}/></span><strong>Una idea.<br/>Muchas posibilidades.</strong><span className="home-paper-line"/><span className="home-paper-line short"/><div className="home-paper-choice"><Check size={14}/><span/></div><div className="home-paper-choice muted"><i/><span/></div></div><span className="home-floating-check"><ShieldCheck size={23}/></span></div></section>
  <AnimatedGroup className="home-metrics">{metrics.map(({label,value,detail,icon:Icon,tone})=><Card key={label} className={`home-metric ${tone==='blue'?'home-metric-primary':''}`}><span className={`studio-stat-icon ${tone}`}><Icon size={21}/></span><p>{label}</p><strong><NumberTicker value={value}/></strong><small>{detail}</small></Card>)}</AnimatedGroup>
  <div className="home-columns"><div className="home-main-column">
   <Card className="home-card"><header className="home-card-heading"><div><h2>Tu ritmo de creación</h2><p>Conjuntos creados en los últimos 7 días · UTC</p></div><Badge variant="secondary">Esta semana</Badge></header><div className="home-chart-summary"><strong><NumberTicker value={weekTotal}/></strong><span>{weekTotal===1?'conjunto creado':'conjuntos creados'}</span></div><div className="home-bars" role="img" aria-label={activity.map(d=>`${d.date}: ${d.sets} conjuntos`).join('; ')}>{activity.map((day,index)=><div className="home-bar-column" key={day.date}><span>{number(day.sets)}</span><div className="home-bar-track"><motion.div initial={reduced?false:{scaleY:0}} animate={{scaleY:1}} transition={{duration:reduced?0:.5,delay:reduced?0:index*.045,ease:"easeOut"}} className={`home-bar ${index===activity.length-1?'current':''}`} style={{height:`${day.sets/maximum*100}%`}}/></div><small>{new Date(`${day.date}T12:00:00Z`).toLocaleDateString('es-MX',{weekday:'short',timeZone:'UTC'})}</small></div>)}</div>{weekTotal===0&&<p className="studio-hint mt-3">Tu próxima creación dará inicio a la actividad de esta semana.</p>}</Card>
   <Card className="home-card home-recent"><header className="home-card-heading"><div><h2>Retoma donde te quedaste</h2><p>Tus conjuntos actualizados recientemente.</p></div><Button asChild variant="ghost" size="sm"><a href="#bank">Ver banco<ArrowUpRight size={15}/></a></Button></header>{recent.length?<div className="home-recent-list">{recent.map(set=><a key={set.id} href={`#set/${set.id}`} className="home-recent-row"><span className="home-file-icon"><FileQuestion size={20}/></span><div className="home-recent-title"><strong>{set.title}</strong><small>{set.specialty} · {set.questions} {set.questions===1?'pregunta':'preguntas'}</small></div><Badge variant="secondary" className={set.reviewed?'studio-reviewed':'studio-pending'}>{set.reviewed?'Revisado':'Por revisar'}</Badge><ArrowUpRight size={17} className="home-row-arrow"/></a>)}</div>:<div className="home-empty"><BookOpen size={32}/><h3>Tu biblioteca empieza aquí</h3><p>Crea tu primer conjunto y vuelve para revisarlo, mejorarlo o practicar.</p><Button asChild variant="outline"><a href="#new">Crear mi primer conjunto<ArrowRight/></a></Button></div>}</Card>
  </div><aside className="home-side-column" aria-label="Revisión y siguientes pasos">
   <Card className="home-card"><header className="home-card-heading"><div><h2>Revisión académica</h2><p>Calidad antes de compartir.</p></div><ShieldCheck size={20} className="text-primary"/></header><div className="home-review-ring" role="img" aria-label={`${percent}% de conjuntos con revisión registrada`}><svg viewBox="0 0 160 160" aria-hidden="true"><circle cx="80" cy="80" r="65" className="home-ring-track"/><motion.circle cx="80" cy="80" r="65" className="home-ring-value" pathLength="100" initial={reduced?false:{strokeDasharray:"0 100"}} animate={{strokeDasharray:`${percent} 100`}} transition={{duration:reduced?0:.7,ease:"easeOut"}} strokeOpacity={percent?1:0}/></svg><div><strong><NumberTicker value={percent}/><small>%</small></strong><span>con revisión</span></div></div><div className="home-review-legend"><span><i/>{number(totals.reviewed)} revisados</span><span><i/>{number(totals.pending)} pendientes</span></div><p className="home-review-note">{totals.sets?'La revisión registrada refleja una comprobación académica manual.':'Cuando crees tu primer conjunto, podrás registrar su revisión aquí.'}</p></Card>
   <Card className="home-next"><span className="home-next-label"><span/> TU SIGUIENTE PASO</span><h2>{nextReview?'Dale una segunda mirada.':totals.sets?'Tus revisiones, al día.':'Prepara tu próxima sesión.'}</h2><p>{nextReview?'Verifica las claves, los distractores y las fuentes de tu conjunto.':totals.sets?'Continúa practicando en tu banco o explora un nuevo tema.':'Convierte un tema y sus fuentes en tu primer conjunto de preguntas.'}</p>{nextReview&&<strong className="home-next-title">{nextReview.title}</strong>}<Button asChild><a href={nextReview?`#set/${nextReview.id}`:'#new'}>{nextReview?'Revisar conjunto':'Empezar a crear'}<ArrowRight size={16}/></a></Button></Card>
   <Card className="home-card"><header className="home-card-heading"><div><h2>Por especialidad</h2><p>Preguntas en todo tu banco.</p></div></header>{specialties.length?<div className="home-specialties">{specialties.map((s,i)=><div key={s.name}><div><span>{s.name}</span><strong>{number(s.questions)}</strong></div><div className="home-specialty-track"><motion.span initial={reduced?false:{scaleX:0}} animate={{scaleX:1}} transition={{duration:reduced?0:.5}} style={{width:`${totals.questions?s.questions/totals.questions*100:0}%`,background:['#4262c9','#8d81c2','#4c9e91','#d69b70'][i%4]}}/></div></div>)}</div>:<p className="studio-hint">Aquí verás la distribución de tus preguntas al crear tu primer conjunto.</p>}</Card>
  </aside></div>
  {(totals.activeRuns>0||totals.failedRuns>0)&&<div className="home-run-notice"><Clock3 size={18}/><p>{totals.activeRuns>0&&`${totals.activeRuns} solicitudes en proceso. `}{totals.failedRuns>0&&`${totals.failedRuns} solicitudes con error en el historial.`}</p><Button asChild variant="ghost" size="sm"><a href="#new">Ver solicitudes<ArrowRight size={15}/></a></Button></div>}
 </div>;
}
