import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Label} from '@/components/ui/label';
import {Badge} from '@/components/ui/badge';
import {api,json,useResource} from '@/lib/api';
import {ErrorNotice,Loading} from './common';
import {QuestionRead} from './SetPage';
import type {ClinicalCase,EvidenceSource} from '../../shared/domain';
type Practice={id:string;setId:string;title:string;revision:number;cases:Array<{id:string;narrative:string;questions:Array<{id:string;stem:string;options:Array<{text:string}>}>}>;answers?:Record<string,number>;feedback?:ClinicalCase[];sources?:EvidenceSource[]};
export function PracticePage({id}:{id:string}){
 const {data,error:loadError,setData}=useResource<Practice>(`/api/practice/${id}`);const [answers,setAnswers]=useState<Record<string,number>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(data){try{setAnswers(data.answers||JSON.parse(localStorage.getItem(`enarm-attempt-${id}`)||'{}'))}catch{setAnswers({})}}},[data,id]);
 function answer(qid:string,value:number){const next={...answers,[qid]:value};setAnswers(next);localStorage.setItem(`enarm-attempt-${id}`,JSON.stringify(next));}
 async function submit(){setBusy(true);setError('');try{const result=await api<{answers:Record<string,number>;feedback:ClinicalCase[];sources:EvidenceSource[]}>(`/api/practice/${id}/submit`,json('POST',{answers}));setData(d=>d?{...d,...result}:d);localStorage.removeItem(`enarm-attempt-${id}`);}catch(e){try{const recovered=await api<Practice>(`/api/practice/${id}`);if(recovered.feedback){setData(recovered);localStorage.removeItem(`enarm-attempt-${id}`);}else setError((e as Error).message)}catch{setError((e as Error).message)}}finally{setBusy(false)}}
 if(loadError)return <ErrorNotice message={loadError}/>;if(!data)return <Loading/>;
 const questions=data.cases.flatMap(c=>c.questions);const answered=questions.filter(q=>answers[q.id]!==undefined).length;const done=!!data.feedback;const score=data.feedback?.flatMap(c=>c.questions).filter(q=>answers[q.id]===q.correctIndex).length;
 return <div className="mx-auto max-w-3xl space-y-6"><header><p className="eyebrow">Vista de prueba · versión {data.revision}</p><h1 className="page-title">{data.title}</h1><p className="page-description">{done?`Resultado: ${score} de ${questions.length} respuestas correctas.`:'Contesta todas las preguntas. Las soluciones y explicaciones se mostrarán al finalizar para evitar pistas entre preguntas seriadas.'}</p><Badge variant="secondary" className="mt-3">{answered} de {questions.length} contestadas</Badge></header><ErrorNotice message={error}/>{data.cases.map((c,ci)=><Card key={c.id} className="shadow-none"><CardHeader><CardTitle>Caso {ci+1}</CardTitle></CardHeader><CardContent className="space-y-6"><p className="rounded-xl bg-muted p-4 text-sm leading-7 whitespace-pre-wrap">{c.narrative}</p>{c.questions.map((q,qi)=><div key={q.id} className="space-y-4 border-t pt-5"><h2 className="font-medium">{qi+1}. {q.stem}</h2><RadioGroup value={answers[q.id]===undefined?'':String(answers[q.id])} onValueChange={v=>answer(q.id,Number(v))} disabled={done} aria-label={`Pregunta ${qi+1} del caso ${ci+1}`}>{q.options.map((o,oi)=><label key={oi} className="flex cursor-pointer items-start gap-3 rounded-lg border p-4 has-[[data-state=checked]]:border-primary has-[[data-state=checked]]:bg-accent"><RadioGroupItem value={String(oi)} id={`${q.id}-${oi}`} className="mt-0.5"/><span className="text-sm leading-6">{String.fromCharCode(65+oi)}. {o.text}</span></label>)}</RadioGroup>{done&&<div className="space-y-4 rounded-lg border p-4"><p className="font-medium text-primary">{answers[q.id]===data.feedback![ci].questions[qi].correctIndex?'Respuesta correcta':'Revisa la explicación'}</p><QuestionRead question={data.feedback![ci].questions[qi]} sources={data.sources||[]}/></div>}</div>)}</CardContent></Card>)}{!done?<Button className="h-12 w-full rounded-full" disabled={answered!==questions.length||busy} onClick={submit}>{busy?'Guardando respuestas…':'Finalizar y ver explicaciones'}</Button>:<Button variant="outline" className="h-11" asChild><a href={`#set/${data.setId}`}>Volver a las preguntas</a></Button>}</div>;
}
