import {useEffect,useState,useRef} from 'react';
import {Save,Download,RefreshCw,Play,BookOpen,ExternalLink,Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Badge} from '@/components/ui/badge';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Label} from '@/components/ui/label';
import {Separator} from '@/components/ui/separator';
import {api,json,navigate,useResource} from '@/lib/api';
import {ErrorNotice,Field,Choice,Loading,type Run} from './common';
import type {QuestionSet,Question,EvidenceSource} from '../../shared/domain';
export function References({question,sources}:{question:Question;sources:EvidenceSource[]}){return <div className="space-y-3">{question.citations.map((citation,i)=>{const source=sources.find(s=>s.id===citation.sourceId);return <details key={i} className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-medium">{source?.kind==='documento'?'Documento propio':'Fuente de biblioteca'} · {source?.title} · página/sección {citation.page}</summary><div className="mt-3 space-y-3"><blockquote className="border-l-2 border-primary pl-3 text-muted-foreground">{citation.quote}</blockquote><p>{citation.claim}</p><p className="text-xs text-muted-foreground">{source?.edition} · consultada {source?.retrievedAt.slice(0,10)}</p><a className="inline-flex items-center gap-2 text-primary underline" href={`${source?.url}${source?.pages.find(p=>p.page===citation.page)?.locator?`#${source.pages.find(p=>p.page===citation.page)!.locator}`:source?.url.endsWith('.pdf')?`#page=${citation.page}`:''}`} target="_blank" rel="noreferrer">Abrir fuente<ExternalLink className="size-3"/></a><details><summary className="cursor-pointer text-muted-foreground">Ver fragmento consultado</summary><p className="mt-3 max-h-64 overflow-auto rounded bg-muted p-3 text-xs leading-6 whitespace-pre-wrap">{source?.pages.find(p=>p.page===citation.page)?.text}</p></details></div></details>})}</div>}
export function QuestionRead({question,sources}:{question:Question;sources:EvidenceSource[]}){return <div className="space-y-4"><h3 className="font-medium">{question.stem}</h3><div className="space-y-2">{question.options.map((o,i)=><div key={i} className={`rounded-lg border p-3 ${i===question.correctIndex?'border-primary/40 bg-accent':''}`}><p className="text-sm font-medium">{String.fromCharCode(65+i)}. {o.text}{i===question.correctIndex&&<Badge variant="outline" className="ml-2">Correcta</Badge>}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{o.explanation}</p></div>)}</div><p className="text-sm leading-6">{question.explanation}</p><References question={question} sources={sources}/></div>}
export function SetPage({id}:{id:string}){
 const {data:set,error:loadError,setData}=useResource<QuestionSet>(`/api/sets/${id}`);
 const [draft,setDraft]=useState<QuestionSet|null>(null);const [editing,setEditing]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [regeneration,setRegeneration]=useState(false);const [instructions,setInstructions]=useState('');const [reviewNote,setReviewNote]=useState('');
 const key=`enarm-draft-${id}`;const pendingRegeneration=useRef<{instructions:string;key:string}|null>(null);
 useEffect(()=>{if(set){try{const stored=localStorage.getItem(key);if(stored){setDraft(JSON.parse(stored));setEditing(true);setNotice('Se recuperaron cambios locales sin guardar.');return;}}catch{}setDraft(structuredClone(set));setInstructions(set.input.instructions);}},[set,key]);
 const dirty=!!draft&&!!set&&JSON.stringify([draft.title,draft.cases])!==JSON.stringify([set.title,set.cases]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function update(change:(next:QuestionSet)=>void){if(!draft)return;const next=structuredClone(draft);change(next);setDraft(next);localStorage.setItem(key,JSON.stringify(next));setNotice('Cambios locales pendientes de guardar.');}
 async function save(){if(!draft)return;setBusy(true);setError('');try{const saved=await api<QuestionSet>(`/api/sets/${id}`,json('PUT',{revision:draft.revision,title:draft.title,cases:draft.cases}));localStorage.removeItem(key);setData(saved);setEditing(false);setNotice('Cambios guardados. La exportación incluye esta versión.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function practice(){setBusy(true);setError('');try{const attempt=await api<{id:string}>(`/api/sets/${id}/practice`,json('POST',{}));navigate(`practice/${attempt.id}`);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function regenerate(){setBusy(true);setError('');try{if(pendingRegeneration.current?.instructions!==instructions)pendingRegeneration.current={instructions,key:crypto.randomUUID()};const run=await api<Run>(`/api/sets/${id}/regenerate`,{...json('POST',{instructions}),headers:{'Content-Type':'application/json','Idempotency-Key':pendingRegeneration.current.key}});sessionStorage.setItem('enarm-current-run',run.id);navigate('new');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function markReviewed(){if(!set)return;setBusy(true);setError('');try{const saved=await api<QuestionSet>(`/api/sets/${id}/review`,json('POST',{revision:set.revision,note:reviewNote}));setData(saved);setNotice('Revisión académica registrada.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loadError)return <ErrorNotice message={loadError}/>;if(!set||!draft)return <Loading/>;
 return <div className="space-y-6"><header><p className="eyebrow">Banco de preguntas · versión {set.revision}</p><h1 className="page-title">{set.title}</h1><div className="mt-4 flex flex-wrap gap-2"><Badge variant="secondary">{set.input.specialty}</Badge><Badge variant="outline">{set.input.difficulty}</Badge><Badge variant="outline">{set.cases.length} casos · {set.cases.flatMap(c=>c.questions).length} preguntas</Badge><Badge variant={set.review_status==='reviewed'?'default':'outline'}>{set.review_status==='reviewed'?'Revisión académica registrada':'Pendiente de revisión académica'}</Badge></div></header>
 <ErrorNotice message={error}/>{notice&&<p role="status" className="text-sm text-primary">{notice}</p>}
 <div className="flex flex-wrap gap-3"><Button className="h-11" variant={editing?'secondary':'outline'} onClick={()=>setEditing(v=>!v)}>{editing?'Vista de lectura':'Editar preguntas'}</Button>{dirty&&<Button className="h-11" onClick={save} disabled={busy}><Save/>Guardar cambios</Button>}<Button className="h-11" variant="outline" disabled={dirty||busy} onClick={practice}><Play/>Contestar prueba</Button><Button className="h-11" variant="outline" asChild disabled={dirty}><a href={dirty?undefined:`/api/sets/${id}/export`} aria-disabled={dirty} onClick={e=>{if(dirty)e.preventDefault()}}><Download/>Exportar JSON</a></Button><Button className="h-11" variant="outline" onClick={()=>setRegeneration(v=>!v)} disabled={dirty||busy}><RefreshCw/>Regenerar conjunto</Button>{dirty&&<Button className="h-11" variant="ghost" onClick={()=>{setDraft(structuredClone(set));localStorage.removeItem(key);setNotice('Se restauró la última versión guardada.');setError('')}}>Descartar cambios locales</Button>}</div>
 {dirty&&<Alert><AlertTitle>Hay cambios sin guardar</AlertTitle><AlertDescription>Guárdalos para incluirlos en la exportación o la prueba. El borrador local se conserva si cambias de pantalla.</AlertDescription></Alert>}
 {regeneration&&<Card><CardHeader><CardTitle>Crear una nueva versión</CardTitle><CardDescription>Se regenerará el conjunto completo para conservar la coherencia de las series. Esta versión y sus ediciones permanecerán guardadas.</CardDescription></CardHeader><CardContent className="space-y-4"><Field id="regeneration" label="Instrucciones para regenerar"><Textarea id="regeneration" value={instructions} maxLength={2000} onChange={e=>setInstructions(e.target.value)}/></Field><Button onClick={regenerate} disabled={busy||dirty}>Generar nueva versión</Button></CardContent></Card>}
 {editing&&<Field id="set-title" label="Título del conjunto"><Input id="set-title" className="h-11" value={draft.title} maxLength={200} onChange={e=>update(d=>{d.title=e.target.value})}/></Field>}
 {set.metadata.issues.length>0&&<Alert><AlertTitle>Comprobaciones y límites</AlertTitle><AlertDescription><ul className="list-disc space-y-1 pl-4">{[...set.metadata.issues.map(i=>i.message),...set.metadata.limitations].map((message,i)=><li key={i}>{message}</li>)}</ul></AlertDescription></Alert>}
 {(editing?draft:set).cases.map((c,ci)=><Card key={c.id} className="min-w-0 shadow-none"><CardHeader><CardTitle className="text-xl">Caso {ci+1} · {c.title}</CardTitle></CardHeader><CardContent className="space-y-6">{editing?<><Field id={`case-title-${ci}`} label={`Título del caso ${ci+1}`}><Input id={`case-title-${ci}`} value={c.title} onChange={e=>update(d=>{d.cases[ci].title=e.target.value})}/></Field><Field id={`case-${ci}`} label={`Caso clínico ${ci+1}`}><Textarea id={`case-${ci}`} value={c.narrative} className="min-h-36" onChange={e=>update(d=>{d.cases[ci].narrative=e.target.value})}/></Field></>:<p className="rounded-xl bg-muted/60 p-5 text-sm leading-7 whitespace-pre-wrap">{c.narrative}</p>}
 {c.questions.map((q,qi)=><div key={q.id} className="space-y-4"><Separator/><p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">Pregunta {qi+1} · {q.topic}{q.subtopic?` / ${q.subtopic}`:''}</p>{editing?<><Field id={`stem-${q.id}`} label="Enunciado"><Textarea id={`stem-${q.id}`} value={q.stem} onChange={e=>update(d=>{d.cases[ci].questions[qi].stem=e.target.value})}/></Field><RadioGroup aria-label={`Respuesta correcta de la pregunta ${qi+1}, caso ${ci+1}`} value={String(q.correctIndex)} onValueChange={v=>update(d=>{d.cases[ci].questions[qi].correctIndex=Number(v)})}>{q.options.map((o,oi)=><div key={oi} className="space-y-3 rounded-lg border p-4"><div className="flex items-center gap-2"><RadioGroupItem id={`correct-${q.id}-${oi}`} value={String(oi)}/><Label htmlFor={`correct-${q.id}-${oi}`}>Marcar opción {String.fromCharCode(65+oi)} como correcta</Label></div><Field id={`option-${q.id}-${oi}`} label={`Opción ${String.fromCharCode(65+oi)}`}><Input id={`option-${q.id}-${oi}`} value={o.text} onChange={e=>update(d=>{d.cases[ci].questions[qi].options[oi].text=e.target.value})}/></Field><Field id={`explanation-${q.id}-${oi}`} label={`Explicación de la opción ${String.fromCharCode(65+oi)}`}><Textarea id={`explanation-${q.id}-${oi}`} value={o.explanation} onChange={e=>update(d=>{d.cases[ci].questions[qi].options[oi].explanation=e.target.value})}/></Field></div>)}</RadioGroup><Field id={`justification-${q.id}`} label="Justificación de la respuesta"><Textarea id={`justification-${q.id}`} value={q.explanation} onChange={e=>update(d=>{d.cases[ci].questions[qi].explanation=e.target.value})}/></Field>
 <div className="space-y-3"><p className="text-sm font-medium">Referencias del contenido</p>{q.citations.map((cite,ri)=><div key={ri} className="space-y-3 rounded-lg border p-3"><Field id={`source-${q.id}-${ri}`} label="Fuente"><Choice id={`source-${q.id}-${ri}`} value={cite.sourceId} items={set.sources.map(s=>[s.id,s.title])} onChange={v=>update(d=>{d.cases[ci].questions[qi].citations[ri].sourceId=v})}/></Field><Field id={`page-${q.id}-${ri}`} label="Página o sección"><Input id={`page-${q.id}-${ri}`} type="number" min={1} value={cite.page} onChange={e=>update(d=>{d.cases[ci].questions[qi].citations[ri].page=Number(e.target.value)})}/></Field><Field id={`quote-${q.id}-${ri}`} label="Cita literal"><Textarea id={`quote-${q.id}-${ri}`} value={cite.quote} onChange={e=>update(d=>{d.cases[ci].questions[qi].citations[ri].quote=e.target.value})}/></Field><Field id={`claim-${q.id}-${ri}`} label="Qué afirmación respalda"><Textarea id={`claim-${q.id}-${ri}`} value={cite.claim} onChange={e=>update(d=>{d.cases[ci].questions[qi].citations[ri].claim=e.target.value})}/></Field><Button variant="ghost" size="sm" disabled={q.citations.length===1} onClick={()=>update(d=>{d.cases[ci].questions[qi].citations.splice(ri,1)})}><Trash2/>Quitar referencia</Button></div>)}<Button variant="outline" size="sm" disabled={q.citations.length>=8} onClick={()=>update(d=>{d.cases[ci].questions[qi].citations.push({sourceId:set.sources[0].id,page:set.sources[0].pages[0].page,quote:'',claim:''})})}><Plus/>Agregar referencia</Button></div>
 </>:<QuestionRead question={q} sources={set.sources}/>}</div>)}
 </CardContent></Card>)}
 {editing&&<Button className="h-12 w-full rounded-full" disabled={!dirty||busy} onClick={save}><Save/>Guardar cambios</Button>}
 <Card className="shadow-none"><CardHeader><CardTitle>Revisión académica</CardTitle><CardDescription>Comprueba el sustento de la clave y los distractores, las unidades, la dificultad y la vigencia de las fuentes.</CardDescription></CardHeader><CardContent className="space-y-4">{set.review_status==='reviewed'&&<p className="rounded-lg bg-accent p-3 text-sm">{set.review_note}</p>}<Field id="review-note" label="Nota de revisión"><Textarea id="review-note" value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Describe qué verificaste y cualquier límite que deba conocer el equipo." maxLength={2000}/></Field><Button variant="outline" disabled={reviewNote.trim().length<10||dirty||busy} onClick={markReviewed}><BookOpen/>Registrar revisión académica</Button></CardContent></Card>
 <details className="rounded-xl border p-4 text-sm"><summary className="cursor-pointer">Modelo, consumo y trazabilidad</summary><div className="mt-3 space-y-2 text-muted-foreground"><p>Generación: {set.metadata.promptVersion}. Las comprobaciones automáticas no sustituyen la revisión médica.</p>{set.metadata.usage.map((u,i)=><p key={i}>{u.purpose==='generation'?'Generación':'Revisión'} · {u.provider==='openrouter'?'OpenRouter · ':''}{u.model} · {u.inputTokens+u.outputTokens} tokens · {(u.durationMs/1000).toFixed(1)} s · {u.estimatedCostUsd===null?'costo no estimado':`US$${u.estimatedCostUsd.toFixed(4)} estimados`}</p>)}{set.parent_id&&<a className="block text-primary underline" href={`#set/${set.parent_id}`}>Abrir versión anterior</a>}</div></details>
 </div>;
}
