import {ExternalLink,FileText} from 'lucide-react';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Button} from '@/components/ui/button';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
import {useResource} from '@/lib/api';
import {Loading,ErrorNotice,type Config,type Doc} from './common';
export function SourcesPage(){const {data:config,error}=useResource<Config>('/api/config');const {data:docs}=useResource<Doc[]>('/api/documents');return <div className="space-y-6"><header><p className="eyebrow">Sustento y trazabilidad</p><h1 className="page-title">Fuentes de consulta</h1><p className="page-description">La biblioteca tiene una cobertura acotada. Puedes ampliarla para una solicitud cargando tu propio documento.</p></header><ErrorNotice message={error}/>{!config&&!error?<Loading/>:null}{config&&<><Alert><AlertTitle>Criterio de selección</AlertTitle><AlertDescription>{config.sourcePolicy}</AlertDescription></Alert><div className="grid gap-4 md:grid-cols-2">{config.library.map(s=><Card key={s.id} className="shadow-none"><CardHeader><CardTitle>{s.title}</CardTitle><CardDescription>{s.edition}</CardDescription></CardHeader><CardContent className="space-y-4"><Badge variant="secondary">{s.specialty}</Badge><p className="text-sm leading-6 text-muted-foreground">Cobertura: {s.topics}.</p><Button variant="outline" className="h-11" asChild><a href={s.url} target="_blank" rel="noreferrer">Consultar fuente<ExternalLink/></a></Button></CardContent></Card>)}</div></>}
 <Card className="shadow-none"><CardHeader><CardTitle>Documentos propios</CardTitle><CardDescription>PDF con texto seleccionable o TXT UTF-8. Máximo 5 MB, 150 páginas de PDF y 800 000 caracteres. Los archivos escaneados o insuficientes se señalan y no sirven como base de generación.</CardDescription></CardHeader><CardContent className="space-y-3">{docs?.length?docs.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><p className="flex items-center gap-2 text-sm break-all"><FileText className="size-4 shrink-0"/>{d.filename}</p><p className="mt-1 text-xs text-muted-foreground">{(d.byte_size/1024).toFixed(0)} KB · {d.extraction_status==='ready'?'Texto extraído':d.extraction_error||'Extracción pendiente'}</p></div><Button variant="outline" asChild><a href={`/api/documents/${d.id}/download`}>Descargar</a></Button></div>):<p className="text-sm text-muted-foreground">Carga un documento desde Nueva solicitud.</p>}</CardContent></Card>
 <Alert><AlertTitle>Qué se comprueba y qué requiere revisión</AlertTitle><AlertDescription>Se comprueba que cada cita aparezca literalmente en su página o sección, junto con la estructura de las preguntas. Una segunda revisión de IA busca contradicciones y respuestas sin sustento. La pertinencia clínica, vigencia, contexto mexicano y calidad académica necesitan revisión humana.</AlertDescription></Alert></div>}
