import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:5174';
const editedTitle=`Conjunto editado ${Date.now()}`;
const source='MATERIAL SINTÉTICO PARA PRUEBAS DE SOFTWARE. No es contenido médico. La señal de ejemplo se clasifica como categoría alfa cuando reúne los indicadores uno y dos. La categoría beta requiere el indicador tres. La categoría gamma requiere el indicador cuatro. No utilizar para docencia clínica.';
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.getByLabel('Tema',{exact:true}).fill('señal');
 await page.getByRole('radio',{name:'Mi documento',exact:true}).check();
 await page.getByLabel('Cargar documento',{exact:true}).setInputFiles({name:'synthetic.txt',mimeType:'text/plain',buffer:Buffer.from(source)});
 await page.getByText('Documento cargado y texto extraído.').waitFor();
 await page.getByRole('radio',{name:'Seriadas',exact:true}).check();
 await page.getByRole('button',{name:'Revisar y generar',exact:true}).click();
 await page.getByRole('dialog',{name:'Revisa tu solicitud'}).waitFor();
 await page.getByRole('button',{name:'Generar preguntas',exact:true}).click();
 await page.getByRole('button',{name:'Revisar preguntas',exact:true}).waitFor({timeout:30000});
 await page.getByRole('button',{name:'Revisar preguntas',exact:true}).click();
 await page.getByRole('heading',{name:'Conjunto sintético de prueba'}).waitFor();
 const setId=page.url().split('set/')[1];
 await page.getByRole('button',{name:'Editar preguntas',exact:true}).click();
 await page.getByLabel('Título del conjunto',{exact:true}).fill(editedTitle);
 await page.getByLabel('Enunciado',{exact:true}).first().fill('¿Qué categoría corresponde a los indicadores uno y dos del escenario editado?');
 await page.getByRole('button',{name:'Guardar cambios',exact:true}).first().click();
 await page.getByText('Cambios guardados. La exportación incluye esta versión.').waitFor();
 const exported=await(await page.request.get(base+`/api/sets/${setId}/export`)).json();assert.equal(exported.title,editedTitle);assert.match(exported.cases[0].questions[0].stem,/escenario editado/);
 await page.reload();await page.getByRole('heading',{name:editedTitle}).waitFor();
 await page.getByRole('button',{name:'Contestar prueba',exact:true}).click();
 await page.getByRole('button',{name:'Finalizar y ver explicaciones'}).waitFor();
 const attemptId=page.url().split('practice/')[1];const before=await(await page.request.get(base+`/api/practice/${attemptId}`)).json();assert.ok(!JSON.stringify(before).includes('correctIndex'));assert.equal(await page.getByText('Correcta',{exact:true}).count(),0);
 await page.getByRole('radiogroup',{name:'Pregunta 1 del caso 1'}).getByRole('radio').first().check();
 await page.getByRole('radiogroup',{name:'Pregunta 2 del caso 1'}).getByRole('radio').nth(1).check();
 await page.getByRole('button',{name:'Finalizar y ver explicaciones'}).click();
 await page.getByText('Resultado: 1 de 2 respuestas correctas.').waitFor();
 await page.reload();await page.getByText('Resultado: 1 de 2 respuestas correctas.').waitFor();
 await page.screenshot({path:'artifacts/clinical-practice.png',fullPage:true});
 await page.getByRole('link',{name:'Volver a las preguntas'}).click();
 await page.getByLabel('Nota de revisión').fill('Revisión sintética de funcionamiento del editor y sus referencias.');
 await page.getByRole('button',{name:'Registrar revisión académica'}).click();await page.getByText('Revisión académica registrada.').waitFor();
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${width}`)}
 await page.screenshot({path:'artifacts/clinical-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Regenerar conjunto',exact:true}).click();await page.getByRole('button',{name:'Generar nueva versión'}).click();
 await page.getByRole('button',{name:'Revisar preguntas',exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Revisar preguntas',exact:true}).click();
 await page.getByText('Modelo, consumo y trazabilidad',{exact:true}).click();
 await page.getByRole('link',{name:'Abrir versión anterior'}).waitFor();
 await page.getByRole('link',{name:'Banco de preguntas',exact:true}).click();await page.getByText(editedTitle,{exact:true}).waitFor();
 await page.getByRole('textbox',{name:'Buscar preguntas'}).fill(editedTitle);await page.getByText(editedTitle,{exact:true}).waitFor();
 await page.getByRole('textbox',{name:'Buscar preguntas'}).fill('no-such-set-for-browser-test');await page.getByText('No hay conjuntos que coincidan con tu búsqueda.').waitFor();
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,setId,checks:['document extraction','series','edit','save','export','reload','practice hides answers','grading','attempt recovery','review','mobile','regeneration preserves previous']}));
} finally {await browser.close()}
