import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { setTimeout } from 'node:timers/promises';
import { migrate } from '../../server/migrate.js';
import { pool, queue } from '../../server/db.js';
import { createApp } from '../../server/app.js';
import { processRun, submitRun } from '../../server/runs.js';
import { RunInput } from '../../shared/domain.js';
import { QUEUE } from '../../server/config.js';
import type { ObjectStore } from '../../server/storage.js';
import { fixtureGenerator, sourceText } from '../fixtures/clinical.js';
const url=process.env.TEST_DATABASE_URL;
if(!url||!['127.0.0.1','localhost'].includes(new URL(url).hostname)||!new URL(url).pathname.endsWith('_test'))throw new Error('Use a local disposable TEST_DATABASE_URL ending in _test');
test('clinical lifecycle: transaction, extraction, series, revision, export, regeneration and solution hiding',async()=>{
 process.env.APP_DB_PASSWORD='local-test-only';process.env.WORKER_DB_PASSWORD='local-test-only';
 await migrate(url);await migrate(url);
 const runtime=(role:string)=>{const u=new URL(url);u.username=role;u.password='local-test-only';return u.toString();};
 const db=pool(runtime('enarm_app'));const workerDb=pool(runtime('enarm_worker'));const boss=queue(runtime('enarm_app'));const worker=queue(runtime('enarm_worker'),false,true);
 const objects=new Map<string,Buffer>();
 const store:ObjectStore={async put(k,b){objects.set(k,b);},async get(k){const b=objects.get(k);if(!b)throw new Error('missing');return b;},async remove(k){objects.delete(k);},async check(){}};
 await boss.start();await worker.start();
 const app=await createApp(db,boss,store,'local-test-only',false);
 const headers={authorization:`Basic ${Buffer.from('enarm:local-test-only').toString('base64')}`,'x-requested-with':'enarm'};
 try {
  await db.query('DELETE FROM enarm.practice_attempts');await db.query('DELETE FROM pgboss.job');await db.query('UPDATE enarm.runs SET parent_set_id=NULL');await db.query('DELETE FROM enarm.question_sets');await db.query('DELETE FROM enarm.runs');await db.query('DELETE FROM enarm.documents');await db.query('DELETE FROM enarm.worker_heartbeat');
  assert.equal((await app.inject('/api/sets')).statusCode,401);
  assert.equal((await app.inject('/api/dashboard')).statusCode,401);
  const emptyDashboard=(await app.inject({url:'/api/dashboard',headers})).json();
  assert.deepEqual(emptyDashboard.totals,{sets:0,questions:0,reviewed:0,pending:0,practices:0,activeRuns:0,failedRuns:0});
  assert.equal(emptyDashboard.activity.length,7);assert.ok(emptyDashboard.activity.every((day:{sets:number})=>day.sets===0));
  assert.deepEqual(emptyDashboard.recent,[]);assert.equal(emptyDashboard.nextReview,null);
  assert.equal((await app.inject({method:'POST',url:'/api/runs',headers:{authorization:headers.authorization},payload:{}})).statusCode,403);
  const base={specialty:'Pruebas',topic:'señal',difficulty:'básica',count:2,format:'seriadas',caseCount:1,questionsPerCase:2,sourceMode:'documento'};
  const boundary='enarm-boundary';
  const upload=await app.inject({method:'POST',url:'/api/documents',headers:{...headers,'content-type':`multipart/form-data; boundary=${boundary}`},payload:Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="fixture.txt"\r\nContent-Type: text/plain\r\n\r\n${sourceText}\r\n--${boundary}--\r\n`)});
  assert.equal(upload.statusCode,201,upload.body);assert.equal(upload.json().extraction_status,'ready');
  const input=RunInput.parse({...base,documentId:upload.json().id});const key=randomUUID();
  assert.equal((await app.inject({method:'POST',url:'/api/runs',headers:{...headers,'idempotency-key':key},payload:input})).statusCode,503);
  await db.query("INSERT INTO enarm.worker_heartbeat(id,generation_ready) VALUES('test',true)");
  const submit=()=>app.inject({method:'POST',url:'/api/runs',headers:{...headers,'idempotency-key':key},payload:input});
  const responses=await Promise.all([submit(),submit()]);assert.equal(responses[0].statusCode,202,responses[0].body);assert.equal(responses[0].json().id,responses[1].json().id);
  const id=responses[0].json().id;
  await assert.rejects(submitRun(db,boss,{...input,topic:'otra'},key));
  assert.equal((await db.query("SELECT count(*)::int AS count FROM pgboss.job WHERE data->>'runId'=$1",[id])).rows[0].count,1);
  await boss.stop();await boss.start();let tries=0;
  await worker.work<{runId:string}>(QUEUE,async jobs=>{for(const job of jobs){if(job.data.runId===id&&tries++===0)throw new Error('transient test failure');await processRun(workerDb,store,job.data.runId,fixtureGenerator);}});
  let run;
  for(let n=0;n<70;n++){run=(await db.query('SELECT * FROM enarm.runs WHERE id=$1',[id])).rows[0];if(run.status==='completed')break;await setTimeout(500);}
  assert.equal(run.status,'completed');assert.equal(tries,2);assert.equal(run.result.clinicalGeneration,true);
  let set=(await app.inject({url:`/api/sets/${id}`,headers})).json();assert.equal(set.cases.length,1);assert.equal(set.cases[0].questions.length,2);assert.equal(set.sources[0].kind,'documento');
  const dashboard=(await app.inject({url:'/api/dashboard',headers})).json();
  assert.equal(dashboard.totals.sets,1);assert.equal(dashboard.totals.questions,2);assert.equal(dashboard.totals.pending,1);
  assert.equal(dashboard.nextReview.id,id);assert.equal(dashboard.recent[0].questions,2);
  assert.deepEqual(dashboard.specialties,[{name:'Pruebas',questions:2}]);
  assert.equal(dashboard.activity.reduce((sum:number,day:{sets:number})=>sum+day.sets,0),1);
  const attempt=(await app.inject({method:'POST',url:`/api/sets/${id}/practice`,headers})).json();
  assert.equal(JSON.stringify(attempt).includes('correctIndex'),false);assert.equal(JSON.stringify(attempt).includes('explanation'),false);
  const edit={revision:set.revision,title:'Título editado',cases:structuredClone(set.cases)};edit.cases[0].questions[0].options[0].text='Alfa modificada';edit.cases[0].narrative+=' Cambio editorial guardado.';
  const saved=await app.inject({method:'PUT',url:`/api/sets/${id}`,headers,payload:edit});assert.equal(saved.statusCode,200,saved.body);assert.equal(saved.json().metadata.reviewedByModel,false);
  assert.equal((await app.inject({method:'PUT',url:`/api/sets/${id}`,headers,payload:edit})).statusCode,409);
  const exported=(await app.inject({url:`/api/sets/${id}/export`,headers})).json();assert.equal(exported.cases[0].questions[0].options[0].text,'Alfa modificada');assert.equal(exported.title,'Título editado');assert.equal(exported.formatVersion,2);
  const partial=await app.inject({method:'POST',url:`/api/practice/${attempt.id}/submit`,headers,payload:{answers:{[set.cases[0].questions[0].id]:0}}});assert.equal(partial.statusCode,422);
  const answers=Object.fromEntries(set.cases[0].questions.map((q:{id:string})=>[q.id,0]));
  const graded=await app.inject({method:'POST',url:`/api/practice/${attempt.id}/submit`,headers,payload:{answers}});assert.equal(graded.statusCode,200,graded.body);assert.equal(graded.json().score,2);assert.equal(graded.json().feedback[0].questions[0].options[0].text,'Categoría alfa');
  assert.equal((await app.inject({method:'POST',url:`/api/practice/${attempt.id}/submit`,headers,payload:{answers}})).statusCode,409);
  const recovered=(await app.inject({url:`/api/practice/${attempt.id}`,headers})).json();assert.ok(recovered.feedback);assert.equal(recovered.revision,1);
  assert.equal((await app.inject({url:'/api/dashboard',headers})).json().totals.practices,1);
  await db.query("UPDATE enarm.worker_heartbeat SET seen_at=now() WHERE id='test'");
  const regen=await app.inject({method:'POST',url:`/api/sets/${id}/regenerate`,headers:{...headers,'idempotency-key':randomUUID()},payload:{instructions:'Nueva variante de ejemplo'}});assert.equal(regen.statusCode,202,regen.body);assert.equal(regen.json().parent_set_id,id);
  assert.equal((await app.inject({url:`/api/sets/${id}`,headers})).json().title,'Título editado');
  const reviewed=await app.inject({method:'POST',url:`/api/sets/${id}/review`,headers,payload:{revision:exported.revision,note:'Revisión sintética para probar el control de versiones.'}});assert.equal(reviewed.statusCode,200);assert.equal(reviewed.json().review_status,'reviewed');
  const reviewedDashboard=(await app.inject({url:'/api/dashboard',headers})).json();
  assert.equal(reviewedDashboard.totals.reviewed,1);assert.equal(reviewedDashboard.recent.find((s:{id:string})=>s.id===id).reviewed,true);
  const download=await app.inject({url:`/api/documents/${input.documentId}/download`,headers});assert.equal(download.body,sourceText);
  const broken={send:async()=>{throw new Error('enqueue failure');}} as unknown as typeof boss;const failedKey=randomUUID();await assert.rejects(submitRun(db,broken,input,failedKey));assert.equal((await db.query('SELECT 1 FROM enarm.runs WHERE idempotency_key=$1',[failedKey])).rowCount,0);
  await assert.rejects(db.query('CREATE TABLE enarm.forbidden(id int)'));await assert.rejects(workerDb.query('CREATE ROLE forbidden'));
 } finally {await app.close();await worker.stop();await boss.stop();await db.end();await workerDb.end();}
});
